apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eqs-web
    environment: production
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eqs-web
      environment: production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eqs-web
        environment: production
    spec:
      containers:
      - image: shithindas/nginx:BUILD_ID
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 1Gi
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /health_check.html
            port: 80
            scheme: HTTP
          periodSeconds: 5
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health_check.html
            port: 80
            scheme: HTTP
          periodSeconds: 5
          initialDelaySeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config-BUILD_ID
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
