---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eqs-web
    environment: production
  name: web-service
spec:
  ports:
  - nodePort: 30163
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: eqs-web
    environment: production
  type: NodePort